### ISSUE TITLE
Availability

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/learn-azure#1]
This issue tracks availability to run sessions.

Sessions will run: **Tuesdays, 2pm-4pm**
:warning: **EXCEPTIONS: Oct 15th, 3pm-5pm; Oct 29th, 3pm-5pm** ⚠️

| Date | Availability | Location |
| --- | --- | --- |
| 24th Sept | | Jack Good |
| 1st Oct | | Asimov/Shelley |
| 8th Oct | No session, clashes with LwM MRO hack day | N/A |
| 15th Oct **3pm-5pm** | No session | Asimov/Shelley |
| 22nd Oct | No session | Augusta Ada |
| 29th Oct **3pm-5pm** | No session | David Blackwell |
| 5th Nov | No Sarah | Asimov/Shelley |
| 12th Nov | No Sarah | Asimov/Shelley |
| 19th Nov | No Sarah | Asimov/Shelley |
| 26th Nov | |Asimov/Shelley|
| 3rd Dec | | Augusta Ada |
| 10th Dec | No session, Turing Data Study Group week | N/A |
| 17th Dec | Drop-in session | Asimov/Shelley |
| 23rd Dec | 🎄| |
| 31st Dec | 🎄| |

cc: @DavidBeavan @thobson88

**Comment by DavidBeavan** [comment]
I'll wait until next Friday before adding my unavailability, when we have the preferred day, as it's day by day sometimes. BTW it looks like Tues 2-4 or 3-5

**Comment by DavidBeavan** [comment]
The Doodle poll has spoken, we are **Tuesdays 14:00-16:00**

**Comment by DavidBeavan** [comment]
@sgibson91 @thobson88 I have updated my availability at the top of this week. Can you both review. @sgibson91 I edited your first week before going away, as you will be here on the Tues, but if you need time for other things then mark yourself as gone again

**Comment by sgibson91** [comment]
@DavidBeavan You were too fast for me! 😂

**Comment by sgibson91** [comment]
I added an extra column for room when we know

**Comment by andrepiza** [comment]
Hi all, we have got a room for all dates until Dec 17th, but for Oct 29th when the largest room available is Turingery (12 people with a BIG squeeze). The option there is to run the training from 3-5pm at David Blackwell (reserved). Let me know. Not sure how to update your comment, @sgibson91 , with room names... In any case, we can now forward the requests to the team (most of them are individual rather than a series as the rooms change through the calendar).

**Comment by DavidBeavan** [comment]
@andrepiza that's brill, thanks so much. Perhaps you can't edit because you don't have permissions on this repo (@sgibson91 is that possible?)

**Executive decision: run Oct 29 in the later slot, great suggestion**

**Comment by sgibson91** [comment]
@DavidBeavan It could be permissions. Though it's a public repo, I image editing someone else's issue is something you'd need permissions for. I can add @andrepiza as admin, or some other role, if that's appropriate?

**Comment by DavidBeavan** [comment]
@sgibson91 yes, it might help continuity across LwM and here, if you're comfy?

**Comment by sgibson91** [comment]
Sure! Will do it now :)

**Comment by andrepiza** [comment]
Perfect. Comment updated with rooms. I actually found Asimov/Shelley av for DEc 10th (Turing DSG week). Should we keep it or is the problem everyone else's availability + risk of being kicked out if DSG needs the space?

**Comment by DavidBeavan** [comment]
@andrepiza it might be good left free, as folk from REG and LwM might be taking part in the DSG. I know I will :)

**Comment by DavidBeavan** [comment]
@andrepiza Thanks for organising this, nice one. BTW I don't think we need 17 Dec, based on my interpretation of 🎄 :) How easy is it to invite the LwM team and @sgibson91 to the room bookings?

**Comment by sgibson91** [comment]
@DavidBeavan I assumed some people may be taking early Christmas break on the 17th, but we could have an open "drop-in" session for those of us who are dedicated?

**Comment by DavidBeavan** [comment]
@sgibson91 @andrepiza a drop-in session on 17 Dec is a good plan, let's keep it in then.

**Comment by andrepiza** [comment]
Ok. So I'm cancelling the room booking for Dec 10th and keeping the booking for Dec 17th. I will send invites now to the team group + @sgibson91 .

**Comment by andrepiza** [comment]
Calendar requests sent. Please let me know if you had any issues - for instance, not getting any of the planned dates. Thanks!

**Comment by sgibson91** [comment]
Closing due to reboot!
