### ISSUE TITLE
How to override network security group rules?

### ISSUE THREAD

**Issue by fedenanni** [alan-turing-institute/learn-azure#18]
I'll drop the question here as it's something I am currently blocked on, which I will probably find a way to solve in the next hours (it might be something super simple, but no idea), but maybe not with an ideal solution.

I want to allow internet connection to our Safe Haven VM for installing `azcopy` and `blobfuse`. To change the security rules I am following these pages:
1. [Network security groups](https://docs.microsoft.com/en-us/azure/virtual-network/security-overview)
2. [Tutorial: Filter network traffic with a network security group using the Azure portal](https://docs.microsoft.com/en-us/azure/virtual-network/tutorial-filter-network-traffic)

The default NSG rules were:

<img width="1748" alt="Screenshot 2020-04-22 at 09 22 47" src="https://user-images.githubusercontent.com/8415204/79958458-d903c180-847a-11ea-9afe-49dd5290d19f.png">

What I added, just to force the situation and allow all internet connections was:

<img width="1749" alt="Screenshot 2020-04-22 at 09 20 02" src="https://user-images.githubusercontent.com/8415204/79958449-d5703a80-847a-11ea-80a0-a79c6bb0e469.png">

However, my VM still doesn't have any internet connection. Issues that I have in mind:

1. My rules don't really override the default ones
2. There's something else that I need to change in Azure that I don't know
3. I should restart the VM to make this happen (I don't think so, but boh)

**Comment by fedenanni** [comment]
Found the issue, I was in the wrong NSG, lol

**Comment by sgibson91** [comment]
Making sure you're manipulating the right resources is always an interesting gotcha in Azure! Closing this for now :)
