### ISSUE TITLE
Session 3: Blob storage

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/learn-azure#8]
https://docs.microsoft.com/en-gb/azure/storage/blobs/storage-quickstart-blobs-cli

**Comment by sgibson91** [comment]
Python version: https://docs.microsoft.com/en-gb/azure/storage/blobs/storage-quickstart-blobs-python

**Comment by sgibson91** [comment]
Example of Python code interacting with Azure Container Registry: https://github.com/HelmUpgradeBot/DockerCleanUp/blob/master/DockerCleanUpBot.py

**Comment by DavidBeavan** [comment]
Thinking about SAS tokens, should we do this with a 'stored access policy':

* https://docs.microsoft.com/en-gb/rest/api/storageservices/define-stored-access-policy
* https://docs.microsoft.com/en-gb/rest/api/storageservices/create-service-sas#specifying-the-signed-identifier

**Comment by sgibson91** [comment]
Closing due to reboot!
